### ISSUE TITLE
Error while downloading videos with title containing '?' sign

### ISSUE THREAD

**Issue by konradstach** [me-majidi/fe-downloader#1]
Script works perfectly fine as long as it doesn't have to deal with videos containing reserved characters. Then it throws an error:
```
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

[Error: ENOENT: no such file or directory, open '*********\81-What is Closure?.srt'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: '*********\81-What is Closure?.srt'
}
```

**Comment by me-majidi** [comment]
It's not related to file name and its characters, it is probably about file system and the directory you are trying to save the file. I think that the directory does not exist.
